### PR TITLE
Header file for drwnGeneralFactor - either a table factor, sparse fac…

### PR DESCRIPTION
**Pull request by xtheunknown0**
…tor or sum of two general factors.

### CODE REVIEW

**Comment by sgould** [comment]
Please change StorageType to drwnFactorStorageType and make sure all private and protected variables start with underscore. THRESHOLD can be made public and static.

Also since this will be the main factor class you should include some test cases to check its functionality and show usage examples. These can be added to the testDarwinPGM application.

**Comment by xtheunknown0** [comment]
I've made the changes you suggested. But if THRESHOLD can be specified by a user (eventually), it can't be static, can it?

Will consider test cases - I'll try to have one factor operation working first.

**Comment by sgould** [comment]
Yes it can be static, but it can't be const (if you want it user specified). Static just means that all instances of the class share the same copy, i.e., you can't tune THRESHOLD for different objects independently.

**Comment by xtheunknown0** [comment]
OK - as long as the user passes a constant double, then the threshold can be const.

**Comment by sgould** [comment]
No static not const. Look at drwnMessagePassingMAPInference or drwnOptimizer for typical examples.

**Comment by xtheunknown0** [comment]
I'm curious - why (make static)?

**Comment by xtheunknown0** [comment]
I'm only interested in seeing the changes to drwnSparseFactor pushed (for now). Is there any way I can enforce that?

**Comment by sgould** [comment]
You can only specify branches to be merged. If you're interested in merging only a subset of the code then it's best to create a separate branch. Include the updated code in that branch and then create a pull request from the newly created branch.

**Pull request closed without merging**
