### PR TITLE
Preliminary version of sparse factor class (contrasting with dense ta…

### PR DESCRIPTION
**Pull request by xtheunknown0**
…ble factor storage using drwnTableFactor).

### CODE REVIEW

**Comment by sgould** [comment]
Please remove the #ifndef FACTOR_H and associated macros. This is handled by #prgama once.
Also the reason for the typedef at the top of the file is not clear.

**Comment by xtheunknown0** [comment]
I've taken into account your comments and committed the cpp file. I think you should see both files for drwnSparseFactor.

**Comment by sgould** [comment]
I've modified the code slightly to be compatible with non-c++11 compilers. Please merge the latest code before continuing development.

**Comment by xtheunknown0** [comment]
I don't know much git. How do I merge?

I got:

chenay@paloalto:~/drwn$ git merge
fatal: No commit specified and merge.defaultToUpstream not set.

<https://www.avast.com/lp-safe-emailing?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/lp-safe-emailing?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sgould** [comment]
Have a look at: https://gun.io/blog/how-to-github-fork-branch-and-pull-request/

Or copy the files drwnSparseFactor.{cpp,h} manually.

**Pull request merged**
